# -------- Build Stage --------
FROM gradle:8.9-jdk17 AS build
WORKDIR /app
COPY --chown=gradle:gradle . .
RUN gradle clean build -x test

# -------- Run Stage --------
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8200

ENTRYPOINT ["java", "-jar", "app.jar"]
